name: hello
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 一个第三方库
  english_words: ^3.1.5
  # 网络请求框架
  dio: ^3.0.7
  # json库
  json_annotation: ^3.0.0
  # https://pub.dev/packages/transparent_image
  transparent_image: ^1.0.0
  # webview 库
  flutter_webview_plugin: ^0.3.10
  # 图片选择
  image_picker: ^0.6.2+3
  # 缓存数据工具
  shared_preferences: ^0.5.6
  # 扫码库（功能比较缺失）
  barcode_scan: ^1.0.0
  # 生成二维码
  qr_flutter: ^3.1.0
  # 下拉刷新，上拉加载
  flutter_easyrefresh: ^2.0.5
  # toast工具
  fluttertoast: ^3.1.3
  # 轮播图
  # flutter_swiper: ^1.0.6
  # 地图
  #  google_maps_flutter: ^0.5.21+13
  # 视频播放插件
  video_player: ^0.10.5
  # 获取硬件信息
  device_info: 0.4.0
  # 汉字转拼音
  lpinyin: ^1.0.7

  #国际化依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/images/fuchsia.jpg
    - assets/images/icon.png

    - assets/images/icon_news_on.png
    - assets/images/icon_news_off.png

    - assets/images/icon_find_on.png
    - assets/images/icon_find_off.png

    - assets/images/icon_mine_on.png
    - assets/images/icon_mine_off.png

    - assets/images/icon_dynamic_on.png
    - assets/images/icon_dynamic_off.png

    - assets/images/icon_arrow_right.png

    - assets/images/icon_avatar_default.png


    - assets/data/country.json
