name: hello
description: a new flutter application.

# the following defines the version and build number for your application.
# a version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# in android, build-name is used as versionname while build-number used as versioncode.
# read more about android versioning at https://developer.android.com/studio/publish/versioning
# in ios, build-name is used as cfbundleshortversionstring while build-number used as cfbundleversion.
# read more about ios versioning at
# https://developer.apple.com/library/archive/documentation/general/reference/infoplistkeyreference/articles/corefoundationkeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # the following adds the cupertino icons font to your application.
  # use with the cupertinoicons class for ios style icons.
  cupertino_icons: ^0.1.2

  # 一个第三方库
  english_words: ^3.1.0
  # 网络请求框架
  dio: ^1.0.6
  # json库
  json_annotation: ^2.0.0
  transparent_image: ^0.1.0
  # webview 库
  flutter_webview_plugin: ^0.2.1+2
  # 图片选择（很多bug，最新版0.6.2+1与kotlin冲突）
  image_picker: ^0.4.1
  # 缓存数据工具
  shared_preferences: ^0.4.2
  # 扫码库（功能比较缺失）
  barcode_scan: ^0.0.8
  # 生成二维码
  qr_flutter: ^3.1.0
  # 下拉刷新，上拉加载https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^1.1.0
  # toast工具
  fluttertoast: ^2.2.6
  # # 轮播图
  # flutter_swiper: ^1.0.6


  #国际化依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# for information on the generic dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# the following section is specific to flutter.
flutter:

  # the following line ensures that the material icons font is
  # included with your application, so that you can use the icons in
  # the material icons class.
  uses-material-design: true

  # to add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # an image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # for details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # to add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. for
  # example:
  # fonts:
  #   - family: schyler
  #     fonts:
  #       - asset: fonts/schyler-regular.ttf
  #       - asset: fonts/schyler-italic.ttf
  #         style: italic
  #   - family: trajan pro
  #     fonts:
  #       - asset: fonts/trajanpro.ttf
  #       - asset: fonts/trajanpro_bold.ttf
  #         weight: 700
  #
  # for details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



  assets:
    - images/fuchsia.jpg
    - images/icon.png

    - images/icon_news_on.png
    - images/icon_news_off.png

    - images/icon_find_on.png
    - images/icon_find_off.png

    - images/icon_mine_on.png
    - images/icon_mine_off.png

    - images/icon_dynamic_on.png
    - images/icon_dynamic_off.png

    - images/icon_arrow_right.png

    - images/icon_avatar_default.png